# Generated by Django 3.0.5 on 2020-06-08 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('in_stock', models.BooleanField(default=True)),
                ('number_in_stock', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('purchased_count', models.PositiveSmallIntegerField(default=0)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('size', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1, null=True)),
                ('clothing_type', models.CharField(choices=[('TS', 'T-Shirt'), ('LS', 'Long Sleeve'), ('ST', 'Sticker')], max_length=2)),
                ('fit', models.CharField(blank=True, choices=[('F', "Women's"), ('M', "Men's"), ('U', 'Unisex')], max_length=1, null=True)),
                ('tag', models.ManyToManyField(related_name='tag', to='shop.Tag')),
            ],
        ),
    ]
