# Generated by Django 3.0.5 on 2020-06-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200608_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='item_images/')),
                ('alt_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ManyToManyField(related_name='image', to='shop.Image'),
        ),
    ]
