# Generated by Django 3.0.5 on 2020-06-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='image', to='shop.Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='size', to='shop.Size'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag', to='shop.Tag'),
        ),
    ]
