# Generated by Django 3.0.5 on 2020-06-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200613_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('TS', 'T-Shirt'), ('LS', 'Long-Sleeve'), ('ST', 'Sticker')], max_length=2),
        ),
    ]
