# Generated by Django 3.0.7 on 2020-07-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_address_order_orderitem_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='being_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
