# Generated by Django 3.0.7 on 2020-07-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200701_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='default',
        ),
    ]
