# Generated by Django 3.0.5 on 2020-07-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_address_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100, null=True, verbose_name='State / Province'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=100, verbose_name='Zip / Postal Code'),
        ),
    ]
