# Generated by Django 3.0.7 on 2020-07-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200701_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='being_processed',
            field=models.BooleanField(default=True),
        ),
    ]
