# Generated by Django 3.0.5 on 2020-07-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200703_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
