# Generated by Django 3.0.5 on 2020-07-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
