# Generated by Django 3.0.5 on 2020-07-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200704_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='being_processed',
            field=models.BooleanField(default=False),
        ),
    ]
