# Generated by Django 3.0.5 on 2020-07-16 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200704_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('review', models.TextField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('rating', models.IntegerField(default=5)),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='shop.Item')),
            ],
        ),
    ]
